### ISSUE TITLE
0.6.4 breaking with userAgent and calc plugin

### ISSUE THREAD

**Issue by adrianleb** [rofrischmann/inline-style-prefixer#55]
Since updating from 0.6.3 to 0.6.4 app started breaking in 2 places:

`userAgent of undefined`: Until now I was initialising the singleton like this:
`let prefixer = new Prefixer();`
this means no options being passed on, breaking the userAgent check. (here: https://github.com/rofrischmann/inline-style-prefixer/blob/master/modules/Prefixer.js#L20)

after changing that to `let prefixer = new Prefixer({});` that error was gone but the lib still crashing, this time:
`Uncaught TypeError: value.indexOf is not a function` on `calc` (here: https://github.com/rofrischmann/inline-style-prefixer/blob/master/modules/plugins/calc.js#L6)

calc is not being used anywhere in my code.

rolling back to `0.6.3` works as expected

**Comment by rofrischmann** [comment]
@adrianleb Thanks for pointing out! 
I will fix this directly and release the fix. According the `calc` plugin: I actually do not understand how this ever worked correctly, as by passing a number, the indexOf breaks (but this should have happened before as well).

**Comment by adrianleb** [comment]
Thanks for the quick fix @rofrischmann!

**Comment by rofrischmann** [comment]
You're welcome :)
